### PR TITLE
fix: A more robust check for rinfo.family 

### LINKED ISSUE #176: Have a more robust check for rinfo.family
As reported on discord [here](https://discord.com/channels/593655374469660673/743858262864167062/973365618772439070) in node version 18 on MacOS, the value of rinfo.family was an integer type 4.

Even though the documentation [here](https://nodejs.org/api/net.html#net_socketaddress_family) states the value should be of type string with value being either 'ipv4' or 'ipv6'. Clearly this is not the case as I was also able to confirm the issue.

This PR makes the check for `rinfo.family` more robust such that it does not fail in this observed mismatch between documentation and behaviour of node/os version.

### PR DESCRIPTION
**Pull request by dadepo**
Closes #176

### CODE REVIEW

**Review by dapplion — APPROVED** [review]
I can approve the PR but have no way to verify it's correct since I don't own a MacOS. Could you look into adding macos tests to demostrate correctness? Github actions have runners for it I think

**Comment by dadepo** [comment]
> Could you look into adding macos tests to demostrate correctness? Github actions have runners for it I think

I checked, github actions do support MacOS but unfortunately M1 is still in currently in public beta. [See](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)

But the main issue seems to be mainly about node version 18. I updated the version in another branch that does not have the fix and was able to confirm the tests fails. [See](https://github.com/ChainSafe/discv5/pull/179)

Updated the same version in this PR, and all tests passes. [See](https://github.com/ChainSafe/discv5/pull/178/commits/3f1eb441f8d577181854074aa0f4a888ab279865). 

So PR should be good to merge.

**Review by dapplion — APPROVED** [review]

**Comment by mpetrunic** [comment]
> > Could you look into adding macos tests to demostrate correctness? Github actions have runners for it I think
> 
> I checked, github actions do support MacOS but unfortunately M1 is still in currently in public beta. [See](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)
> 
> But the main issue seems to be mainly about node version 18. I updated the version in another branch that does not have the fix and was able to confirm the tests fails. [See](https://github.com/ChainSafe/discv5/pull/179)
> 
> Updated the same version in this PR, and all tests passes. [See](https://github.com/ChainSafe/discv5/pull/178/commits/3f1eb441f8d577181854074aa0f4a888ab279865). 
> 
> So PR should be good to merge. 
> 

I can run it locally on m1 if you are concerned

**Comment by dadepo** [comment]
> I can run it locally on m1 if you are concerned

Thanks! 🙏 But that should not be needed anymore. Plus I do have an M1 and was able to verify the issue/fix.

**Pull request merged**
